export { default as HeadMarkIcon } from './HeadMark'
export { default as FireIcon } from './Fire'
export { default as InfoFullCircleIcon } from './InfoFullCircle'
export { default as MarkIcon } from './Mark'
export { default as SquareCheckIcon } from './SquareCheck'
