import type { Metadata } from 'next'

import Header from '@/components/header'
import SolanaProvider from '@/providers/solana.provider'
import StoreProvider from '@/providers/store.provider'
import TanstackProviders from '@/providers/tanstack.provider'
import { Suspense } from 'react'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import '../../styles/index.scss'
import './../globals.css'

export const metadata: Metadata = {
  title: 'Golden Apple BRC20',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  locale,
}: Readonly<{
  children: React.ReactNode
  locale: never
}>) {
  return (
    <html lang={locale || 'en'}>
      <TanstackProviders>
        <StoreProvider>
          <SolanaProvider>
            <body className="bg-[#FAF5F0] bg-full bg-fixed">
              <Suspense>
                <Header />
                {children}
                <ToastContainer
                  position="top-right"
                  className="z-[10000]"
                  autoClose={5000}
                  hideProgressBar
                  closeOnClick
                />
              </Suspense>
            </body>
          </SolanaProvider>
        </StoreProvider>
      </TanstackProviders>
    </html>
  )
}

