import type { Metadata } from 'next'

import Header from '@/components/header'
import SolanaProvider from '@/providers/solana.provider'
import ReduxStoreProvider from '@/providers/store.provider'
import TanstackProviders from '@/providers/tanstack.provider'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'

import { Suspense } from 'react'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { languages } from '../../i18n/setting'
import '../../styles/index.scss'
import './globals.css'

export const metadata: Metadata = {
  title: 'Golden Apple BRC20',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return languages.map((locale) => ({ locale }))
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: never
}>) {
  const messages = await getMessages()
  return (
    <html lang={locale}>
      <TanstackProviders>
        <ReduxStoreProvider>
          <SolanaProvider>
            <NextIntlClientProvider messages={messages}>
              <body className="bg-[#FAF5F0] bg-full bg-fixed">
                <Suspense>
                  <Header />
                  {children}
                  <ToastContainer
                    position="top-right"
                    className="z-[10000]"
                    autoClose={5000}
                    hideProgressBar
                    closeOnClick
                  />
                </Suspense>
              </body>
            </NextIntlClientProvider>
          </SolanaProvider>
        </ReduxStoreProvider>
      </TanstackProviders>
    </html>
  )
}

