name: Build

on:
  push:
    branches:
      - update/ui/reskin

env:
  REGISTRY_PATH: 339712905004.dkr.ecr.ap-southeast-1.amazonaws.com/golden-apple
  REPO_NAME: ${{ github.event.repository.name }}
  # BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        run: |
          export ts=`date +%s`
          docker build -t $REGISTRY_PATH:$REPO_NAME-prod-ga-$GITHUB_SHA-$ts .
          docker build -t $REGISTRY_PATH:$REPO_NAME-latest .

          docker push $REGISTRY_PATH:$REPO_NAME-prod-ga-$GITHUB_SHA-$ts
          docker push $REGISTRY_PATH:$REPO_NAME-latest
